url = "http://localhost:8501"
SUPABASE_URL="https://kuiatozibtgbonikirci.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1aWF0b3ppYnRnYm9uaWtpcmNpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTIwODI2MywiZXhwIjoyMDk0Nzg0MjYzfQ.I9rCWbOhJk_fME7DDUvYaN1KCtCFPvlWwoTgiXzB4Vs"
SUPABASE_ANON_KEY = "sb_publishable_g5zWnZnVpcX93AYXaMZckw_Y61tH6WW"

client_id = "766498778772-78uvjrtig2q9dbqqgrjvpdtqnk4qijl5.apps.googleusercontent.com"
client_secret = "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"
redirect_url = "http://localhost:8501"
